export default {
  dinosaurs: [
    {
      name: "Allosaurus",
      diet: "carnivorous",
      period: "Late Jurassic",
      type: "Large theropod",
      imgsrc:
        "https://thenaturalworld1.blogspot.com/2012/12/23-fact-tuesday-allosaurus.html",
    },
    {
      name: "Archaeopteryx",
      diet: "carnivorous",
      period: "Late Jurassic",
      type: "Small theropod",
      imgsrc:
        "https://gardenofeaden.blogspot.com/2012/03/dinosaur-archaeopteryx.html",
    },
    {
      name: "Ceratosaurus",
      diet: "carnivorous",
      period: "Late Jurassic",
      type: "Large theropod",
      imgsrc:
        "https://en.wikipedia.org/wiki/File:Ceratosaurus_nasicornis_DB.jpg",
    },
    {
      name: "Conchoraptor",
      diet: "carnivorous",
      period: "Late Cretaceous",
      type: "Small theropod",
      imgsrc: "http://www.wikidino.com/?page_id=384",
    },
    {
      name: "Deinonychus",
      diet: "carnivorous",
      period: "Early Cretaceous",
      type: "Small theropod",
      imgsrc: "http://dinosaurios.org/deinonychus/",
    },
    {
      name: "Irritator",
      diet: "carnivorous",
      period: "Early Cretaceous",
      type: "Large theropod",
      imgsrc: "http://dinosaurkingfanon.wikia.com/wiki/File:Irritator.jpg",
    },
    {
      name: "Liliensternus",
      diet: "carnivorous",
      period: "Late Triassic",
      type: "Small theropod",
      imgsrc: "http://www.dinosaurfact.net/Triassic/Liliensternus.php",
    },
    {
      name: "Megalosaurus",
      diet: "carnivorous",
      period: "Mid Jurassic",
      type: "Large theropod",
      imgsrc: "http://www.wikidino.com/?attachment_id=3395",
    },
    {
      name: "Microraptor",
      diet: "carnivorous",
      period: "Early Cretaceous",
      type: "Small theropod",
      imgsrc: "http://dinosaurs.wikia.com/wiki/File:Microraptor_gui.jpg",
    },
    {
      name: "Ornitholestes",
      diet: "carnivorous",
      period: "Late Jurassic",
      type: "Small theropod",
      imgsrc: "https://en.wikipedia.org/wiki/File:Ornitholestes_BW.jpg",
    },
    {
      name: "Proceratosaurus",
      diet: "carnivorous",
      period: "Mid Jurassic",
      type: "Small theropod",
      imgsrc:
        "http://jpl-live-the-legend.wikia.com/wiki/Proceratosaurus_bradleyi_%22amplus%22",
    },
    {
      name: "Spinosaurus",
      diet: "carnivorous",
      period: "Late Cretaceous",
      type: "Large theropod",
      imgsrc: "https://www.bbc.co.uk/nature/life/Spinosaurus",
    },
    {
      name: "Tyrannosaurus",
      diet: "carnivorous",
      period: "Late Cretaceous",
      type: "Large theropod",
      imgsrc: "http://1ms.net/tyrannosaurus-dinosaurs-284222.html",
    },
    {
      name: "Velociraptor",
      diet: "carnivorous",
      period: "Late Cretaceous",
      type: "Small theropod",
      imgsrc: "http://www.famouscutouts.com/raptor.html",
    },
    {
      name: "Amygdalodon",
      diet: "herbivorous",
      period: "Mid Jurassic",
      type: "Sauropod",
      imgsrc:
        "https://hiurieosdinossauros.blogspot.com/2011/10/amygdalodon.html",
    },
    {
      name: "Ankylosaurus",
      diet: "herbivorous",
      period: "Late Cretaceous",
      type: "Armoured dinosaur",
      imgsrc:
        "https://trodinswebosaurcheats.wordpress.com/2010/10/16/snarls-dino-facts-ankylosaurus/",
    },
    {
      name: "Brachiosaurus",
      diet: "herbivorous",
      period: "Late Jurassic",
      type: "Sauropod",
      imgsrc:
        "By Nobu Tamura email: nobu.tamura@yahoo.com - http://spinops.blogspot.com/2016/12/brachiosaurus-altithorax.html",
    },
    {
      name: "Camptosaurus",
      diet: "herbivorous",
      period: "Late Jurassic",
      type: "Euornithopod",
      imgsrc: "http://www.palimpalem.com/3/dinosaurios/body20.html",
    },
    {
      name: "Chaoyangsaurus",
      diet: "herbivorous",
      period: "Late Jurassic",
      type: "Ceratopsian",
      imgsrc: "https://es.wikipedia.org/wiki/Archivo:Chaoyangsaurus_BW.jpg",
    },
    {
      name: "Diplodocus",
      diet: "herbivorous",
      period: "Late Jurassic",
      type: "Sauropod",
      imgsrc:
        "http://fineartamerica.com/featured/diplodocus-michael-vigliotti.html",
    },
    {
      name: "Gilmoreosaurus",
      diet: "herbivorous",
      period: "Late Cretaceous",
      type: "Euornithopod",
      imgsrc: "http://www.wikidino.com/?tag=gilmoreosaurus",
    },
    {
      name: "Iguanodon",
      diet: "herbivorous",
      period: "Early Cretaceous",
      type: "Euornithopod",
      imgsrc: "https://sauropedia.wordpress.com/2011/05/17/iguanodon/",
    },
    {
      name: "Parasaurolophus",
      diet: "herbivorous",
      period: "Late Cretaceous",
      type: "Euornithopod",
      imgsrc: "https://jurassicworld-evolution.fandom.com/wiki/Parasaurolophus",
    },
    {
      name: "Stegosaurus",
      diet: "herbivorous",
      period: "Late Jurassic",
      type: "Armoured dinosaur",
      imgsrc:
        "https://thenaturalworld1.blogspot.com/2012/07/the-thagomizer-of-stegosaurus.html",
    },
    {
      name: "Triceratops",
      diet: "herbivorous",
      period: "Late Cretaceous",
      type: "Ceratopsian",
      imgsrc: "http://dinosaurios.org/",
    },
    {
      name: "Caudipteryx",
      diet: "omnivorous",
      period: "Early Cretaceous",
      type: "Small theropod",
      imgsrc: "https://www.britannica.com/animal/Caudipteryx",
    },
    {
      name: "Coloradisaurus",
      diet: "omnivorous",
      period: "Late Triassic",
      type: "Sauropod",
      imgsrc: "http://www.wikidino.com/?attachment_id=16999",
    },
    {
      name: "Gallimimus",
      diet: "omnivorous",
      period: "Late Cretaceous",
      type: "Large theropod",
      imgsrc: "https://jurassicpark.fandom.com/wiki/Gallimimus",
    },
    {
      name: "Khaan",
      diet: "omnivorous",
      period: "Late Cretaceous",
      type: "Small theropod",
      imgsrc: "https://t-pekc.deviantart.com/art/Khaan-mckennai-113557485",
    },
    {
      name: "Nothronychus",
      diet: "omnivorous",
      period: "Late Cretaceous",
      type: "Large theropod",
      imgsrc: "http://carnivoraforum.com/topic/9339358/",
    },
    {
      name: "Oviraptor",
      diet: "omnivorous",
      period: "Late Cretaceous",
      type: "Small theropod",
      imgsrc: "https://en.wikipedia.org/wiki/File:Oviraptor_on_nest_037.JPG",
    },
    {
      name: "Struthiomimus",
      diet: "omnivorous",
      period: "Late Cretaceous",
      type: "Small theropod",
      imgsrc: "https://jurassicworld-evolution.fandom.com/wiki/Struthiomimus",
    },
  ],
};
